---
openapi: 3.0.0
info:
  title: Open Transport API
  description: Central look-up / directory for referencing operator API locations and associated data, and available transport modes. V1.1.0 incorporates CR001 (The addition of another "mode”, that of “016 - suspended cable car in reference implementation at https://open-transport.azure-api.net/mode”), CR002 (Change of API structure to align to PAS212, reference implementation at https://open-transport.azure-api.net/operator), and CR003 (Expansion of the look-up service to include MIPTA (Mobile Interface for Public Transport Assets) asset registry endpoint location (URL))
  contact:
    email: hayden@idealinterface.co.uk
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.1.0
servers:
- url: https://virtserver.swaggerhub.com/open-transport/operator-info/1.1.0
  description: SwaggerHub API Auto Mocking
tags:
- name: operators
  description: Secured operator-only calls
- name: developers
  description: Operations available to regular developers
host: "encoded-net-317015.appspot.com"
paths:
  /mode:
    get:
      tags:
      - developers
      summary: returns available modes of transport
      description: |
        Simple list of available modes of transport
      operationId: getMode
      responses:
        "200":
          description: results matching criteria
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/mode'
        "400":
          description: bad input parameter
  /operator:
    get:
      tags:
      - developers
      summary: returns registered operators in PAS212:2016 compliant format
      description: |
        PAS212 compliant list of operators
      operationId: getOperator
      parameters:
      - name: filterString
        in: query
        description: pass an optional filter string for looking up operators
        required: false
        style: form
        explode: true
        schema:
          type: string
      responses:
        "200":
          description: results matching criteria
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/operator'
        "400":
          description: bad input parameter
components:
  schemas:
    operator:
      required:
      - catalogue-metadata
      - items
      type: object
      properties:
        catalogue-metadata:
          type: array
          items:
            $ref: '#/components/schemas/operator_cataloguemetadata'
        items:
          type: array
          items:
            $ref: '#/components/schemas/operator_items'
    mode:
      required:
      - id
      type: object
      properties:
        id:
          type: string
          example: "010"
        short-desc:
          type: string
          example: train
        long-desc:
          type: string
          example: includes intercity, Eurostar / TGV, etc.
      description: Details of the available modes of transport
    operator_cataloguemetadata:
      required:
      - rel
      - val
      type: object
      properties:
        rel:
          type: string
        val:
          type: string
    operator_items:
      required:
      - href
      - item-metadata
      type: object
      properties:
        href:
          type: string
        item-metadata:
          type: array
          items:
            $ref: '#/components/schemas/operator_cataloguemetadata'
